### ISSUE TITLE
Not removing ads?

### ISSUE THREAD

**Issue by argonan0** [KBlixt/subcleaner#26]
Ran on a sub but nothing was processed and these lines were not removed:

> Support us and become VIP member to remove all ads from www.OpenSubtitles.org

> Please rate this subtitle at www.osdb.link/xyz Help other users choose the best subtitles.

**Comment by KBlixt** [comment]
Could you send me the log? And which file you experienced this for?

**Comment by KBlixt** [comment]
While I could change permissions on a file with python its not possible to do so without the correct permissions in the first place.

Sorry.

**Comment by KBlixt** [comment]
Errr, OK. Strange root doesn't have write permissions.

But if it works, it works 👍
