### ISSUE TITLE
Provide an option to remove id #s X, Y, Z

### ISSUE THREAD

**Issue by winbatch** [KBlixt/subcleaner#30]
Let's say I do a dry run and I like 2 of the 3 changes it would do.  How can I say only do #1 and #3 but not number 2?

**Comment by winbatch** [comment]
Actually, I think I'm looking for exactly what you offer with respect to warnings, but just looking for it for non warnings in dry run mode.  If this already exists and I missed it, my apologies.

**Comment by KBlixt** [comment]
Mh, that's not really possible, sorry. Not really sure how I could implement it either. It would be better to modify the regex so it no longer register the second as a false positive.

As you say you can use the destroy option but I'd very careful with that option and always run it with dry-run and confirm before running it for real.
