### ISSUE TITLE
False Positive on Season X Episode X

### ISSUE THREAD

**Issue by araujojr82** [KBlixt/subcleaner#36]
Hi, I'm trying to build a Portuguese REGEX file, and in my tests I stumbled upon this regex on the global.conf:
global_purge3: s(eason)?\W*\d+[^,]\W*e(pisode)?\W*\d+[^,]

This Regex is removing the following line from my file:

          |     00:21:19,280 --> 00:21:21,760
          |     casos famosos,
          |     especialmente nos anos 70 e 80,

Which translates to 
"famous cases,
especially in the 70s and 80s,"

It is matching this part: ano**s 70 e 80**.

I think a good solution for this would be to check the character before the 's(eason)', is this possible somehow?

**Comment by KBlixt** [comment]
I added a word break infront of the s in the mention regex so that this should no longer be an issue while not breaking any existing solutions.

Give it a try and let me know 👍
