### ISSUE TITLE
Opportunity to add groups

### ISSUE THREAD

**Issue by frasderp** [KBlixt/subcleaner#39]
Saw these as warnings today, maybe can be added as specific groups to block (or refine the regex?)

          |                                         [---------Warning Blocks----------]
          |                                         1380
          |                                         02:40:47,009 --> 02:40:55,211
          |                                         Resynced for Media Player by SourGrass :-))
          |                                         [---------------------------------]
		  
		            |                                         [---------Warning Blocks----------]
          |                                         7
          |                                         00:00:24,980 --> 00:00:31,980
          |                                         Ripped By mstoll
          |                                         reasons: (en_warn1, en_warn2)
          |                                         [---------------------------------]
		  
          |                                         [---------Warning Blocks----------]
          |                                         32
          |                                         00:02:05,799 --> 00:02:09,931
          |                                         transcripted by alire2a
          |                                         alirezae973@gmail.com
          |                                         reasons: (global_warn1, global_warn1)
          |                                         [---------------------------------]

**Comment by KBlixt** [comment]
Done 👍
