### ISSUE TITLE
Improve documentation for config setting

### ISSUE THREAD

**Issue by VicePrez** [KBlixt/subcleaner#62]
Just a suggestion to improve the documentation under `README.md`:

It's probably worth adding that the `default_language` in the config file only accepts `ISO_639` language codes only. Maybe even add a link to the wikipedia page?

[https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes](url)

You do mention the following in the default config file, but it may be missed if someone was just following your github docs.

> Set which **language code** subtitles is considered to have if the script is called without specifying language.

**Comment by KBlixt** [comment]
Sorry, but if the reader of this document is unable to Google "language code" and picking the first result I'd have to clarify a lot of things in the documentation in this project which would hurt readability for everyone else. Furthermore, when working with language codes for srt files it's in that documentation already, so I'd only have to clarify this if I was breaking common practice. 

Im refering to the term for a lot in the documentation so would become quite wordy.

I do refer to iso_639 in the --help printout.
