### ISSUE TITLE
Invalid Start Byte

### ISSUE THREAD

**Issue by televisi** [KBlixt/subcleaner#9]
Hi,

I'm trying to run the script against one of the srt files, unfortunately it thrown the following error:
```
root@bazaar:/movies/The Expendables - 2010# python3 /config/script/subcleaner/subcleaner.py --dry-run File.en.srt 
subcleaner was unable to decode file: "Files.en.srt
" reason: "invalid start byte"
subcleaner completed successfully.
```

I have attached the srt file for your reference.

Thanks
[Files.en.srt.zip](https://github.com/KBlixt/subcleaner/files/9067570/Files.en.srt.zip)

**Comment by televisi** [comment]
Sorry, it was a rename issue; originally it has a movie name; but I renamed it to "Files.en.srt" for obvious reason (don't want to share the full movie names here hehe.

I did try to rename the file, unfortunately, same error.

The following is the original runs:

`root@bazaar:/movies/The Expendables - 2010# python3 /config/script/subcleaner/subcleaner.py --dry-run *.srt
subcleaner was unable to decode file: "/movies/The Expendables - 2010/The Expendables - DVD-Rip.en.srt
" reason: "invalid start byte"
SUBTITLE: "/movies/The Expendables - 2010/The Expendables - DVD-Rip.id.srt"
    [INFO]: Nothing will be altered, (Dry-run).
    [INFO]: Didn't run language detection.
    [INFO]: Removed 0 subtitle blocks.

[---------------------------------------------------------------------------------]
subcleaner completed successfully.
root@bazaar:/movies/The Expendables - 2010# cp "The Expendables - DVD-Rip.en.srt" File.en.srt
root@bazaar:/movies/The Expendables - 2010# python3 /config/script/subcleaner/subcleaner.py --dry-run *.srt
subcleaner was unable to decode file: "/movies/The Expendables - 2010/File.en.srt
" reason: "invalid start byte"
subcleaner was unable to decode file: "/movies/The Expendables - 2010/The Expendables - DVD-Rip.en.srt
" reason: "invalid start byte"
SUBTITLE: "/movies/The Expendables - 2010/The Expendables - DVD-Rip.id.srt"
    [INFO]: Nothing will be altered, (Dry-run).
    [INFO]: Didn't run language detection.
    [INFO]: Removed 0 subtitle blocks.

[---------------------------------------------------------------------------------]
subcleaner completed successfully.
`

**Comment by KBlixt** [comment]
If the file have been encoded incorrectly and the uploaded to the site then scripts that are a bit less robustly such as this one could have issues reading the files. try to create a new file and copy the text from the old file into the new file. sometimes this helps.

**Comment by KBlixt** [comment]
Yep, looking at the file more carefully it has been encoding using "Windows-1252" instead of something more standard like UTF-8 or ASCII. 

This is why subcleaner fail to open the file.  I've added to the script that it tries to open with that encoding as well before giving up.  so If you update the script it should work.

**Comment by televisi** [comment]
Thank you, this fixed my issue
